name: "Populate Known Host"
description: "Store remote host SSH key in known_hosts"

inputs:
  ssh-username:
    description: "SSH username"
    default: "ubuntu"
    required: true
  ssh-host:
    description: "SSH host"
    required: true
  ssh-port:
    description: "SSH port"
    default: "22"
    required: false

runs:
  using: "composite"
  steps:
    - name: Add remote host SSH key
      run: ssh-keyscan ${{ inputs.ssh-host }} >> ~/.ssh/known_hosts
      shell: bash
