name: "Execute Commands Remotely"
description: "Send commands and run them remotely"

inputs:
  ssh-username:
    description: "SSH username"
    default: "ubuntu"
    required: true
  ssh-host:
    description: "SSH host"
    required: true
  ssh-port:
    description: "SSH port"
    default: "22"
    required: false
  ssh-command:
    description: "SSH command"
    required: true

runs:
  using: "composite"
  steps:
    - name: Send remote commands
      run: ssh -o StrictHostKeyChecking=no ${{ inputs.ssh-username }}@${{ inputs.ssh-host }} "${{ inputs.ssh-command }}"
      shell: bash
