name: Dockerfile CI

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'Dockerfile.reservoir'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile.reservoir
        tags: beam-indexer:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        load: true

    - name: Upload new cache
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache-new
        key: ${{ runner.os }}-buildx-${{ github.sha }}
