name: Reload Reservoir process
on:
  workflow_dispatch:

run-name: ${{ github.workflow }} by @${{ github.actor }} from ${{ github.ref_name }}

jobs:
  reload-reservoir:
    runs-on: self-hosted
    environment: Production
    strategy:
      fail-fast: false
      matrix:
        node: [
          BEAM_13337_RESERVOIR_MAIN, 
          BEAM_13337_RESERVOIR_SECONDARY,
          
          BEAM_4337_RESERVOIR_MAIN,
          BEAM_4337_RESERVOIR_SECONDARY,
          
          IMX_13473_RESERVOIR_MAIN,
          IMX_13473_RESERVOIR_SECONDARY,

          IMX_13371_RESERVOIR_MAIN,
          IMX_13371_RESERVOIR_SECONDARY,
          ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Reload reservoir processes on all nodes
        uses: ./.github/actions/send-remote-commands
        with:
          ssh-host: ${{ secrets[matrix.node] }}
          ssh-command: |
            sudo systemctl restart reservoir
